# Generated by Django 2.2.7 on 2019-11-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChefAssist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.CharField(max_length=800),
        ),
    ]
